name: tracker

services:
 user-service:
  build: user-service
  image: user:1.2.8
  environment:
    SPRING_PROFILES_ACTIVE: docker
    DB_LOGIN: user_krainet
    DB_PASSWORD: 855312
    MAIL_LOGIN_APP: ${MAIL_APP}
    MAIL_PASSWORD_APP: ${MAIL_PASSWORD_APP}
  networks:
   - tracker-network
 pg_db:
  build: postgresql
  image: postgresql-tracker:1.2.8
  environment:
   POSTGRES_USER: tracker_admin
   POSTGRES_PASSWORD: 855312
  networks:
   - tracker-network
 pgadmin:
  build: pgadmin
  image: pgadmin-tracker:1.2.8
  environment:
   PGADMIN_DEFAULT_EMAIL: admin1@tracker.com
   PGADMIN_DEFAULT_PASSWORD: tracker
  ports:
   - 85:80
  networks:
   - tracker-network
 proxy:
  build: proxy
  image: proxy-tracker:1.2.8
  ports:
   - 80:80
  networks:
   - tracker-network
   
networks:
 tracker-network: