CREATE ROLE user_krainet WITH
	LOGIN
	NOSUPERUSER
	CREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1
	PASSWORD '855312';

CREATE DATABASE krainet
	WITH
	OWNER=user_krainet
	ENCODING='UTF8'
	CONNECTION LIMIT=-1
	IS_TEMPLATE=False;